services:
  music-tool:
    build: .
    container_name: music-tool-web
    ports:
      - "5001:5000"    # Web 界面端口 (避免与ControlCenter冲突)
    volumes:
      # 将宿主机的目录挂载到容器中
      - ./input:/app/input          # 输入文件目录
      - ./output:/app/output        # 输出文件目录
      - ./temp:/app/temp           # 临时文件目录
      - ./uploads:/app/uploads     # 上传文件目录
      # 如果需要处理现有的音频文件，可以挂载更多目录
      - ./m4s:/app/m4s             # M4S 文件目录
    environment:
      - PYTHONPATH=/app
      - PYTHONIOENCODING=utf-8
      - FLASK_APP=web_app.py
      - FLASK_ENV=production
    restart: unless-stopped
    working_dir: /app
